version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - backend
    env_file:
      - .env
    volumes:
      - .:/var/www/html/  # ✅ Sync local files with container
      - /var/www/html/node_modules  # ✅ Prevent overwriting node_modules
    ports:
      - "30001:3000"
    container_name: bizz-app
    restart: unless-stopped  # ✅ Ensures container restarts if it crashes

  mysql:
    image: mysql:latest
    restart: always
    networks:
      - backend
    environment:
      - MYSQL_ROOT_USER=${DB_USER}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}  # ✅ Required for root user
      - MYSQL_DATABASE=${DB_NAME}  # ✅ Creates a database
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    volumes:
      - mysql_data:/var/lib/mysql  # ✅ Persist database data
    container_name: bizz-mysql-app

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: bizz-phpmyadmin-app
    platform: linux/amd64
    depends_on:
      - mysql
    networks:
      - backend
    env_file:
      - .env
    environment:
      - PMA_HOST=mysql  # ✅ Connect phpMyAdmin to MySQL container
      - PMA_PORT=3306
    ports:
      - "30002:80"
    restart: unless-stopped  # ✅ Ensures phpMyAdmin restarts if needed

networks:
  backend:
     driver: bridge


volumes:
  mysql_data:  # ✅ Persistent MySQL storage to avoid losing data