version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: bizznest/bizznest-flow
    depends_on:
      - mysql
    networks:
      - backend
    environment:
      - DB_HOST=bizz-mysql-app  # ✅ Correct MySQL container name
      - DB_USER=root
      - DB_PASSWORD=yoyo2002
      - DB_NAME=bizznestflow2
      - DB_PORT=3360
    volumes:
      - ./:/var/www/html/
    ports:
      - "30001:3000"
    container_name: bizz-app

  mysql:
    image: mysql:latest
    restart: always
    networks:
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD=yoyo2002  # ✅ Root password
      - MYSQL_DATABASE=bizznestflow2  # ✅ Your database name
    ports:
      - "3360:3306"  # ✅ Map MySQL 3306 to host port 3360
    container_name: bizz-mysql-app

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    platform: linux/amd64  # ✅ Needed for Apple M1/M2 (ARM-based Macs)
    depends_on:
      - mysql
    networks:
      - backend
    ports:
      - "30002:80"
    environment:
      - PMA_HOST=bizz-mysql-app  # ✅ Must match MySQL container name
      - PMA_PORT=3306
    container_name: bizz-phpmyadmin-app

networks:
  backend: