version: "3.8"

services:
  backend-development:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - backend
    env_file:
      - .env
    container_name: bizz-app
    restart: unless-stopped  # ✅ Ensures container restarts if it crashes

  mysql:
    image: mysql:latest
    restart: always
    networks:
      - backend
    environment:
      - MYSQL_ROOT_USER=${DB_USER}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}  # ✅ Required for root user
      - MYSQL_DATABASE=${DB_NAME}  # ✅ Creates a database
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 5s
      retries: 20
    volumes:
      - mysql_data:/var/lib/mysql  # ✅ Persist database data
    container_name: bizz-mysql-app

  nginx:
    build:
      context: ../proxy/career-harvest/proxy
      dockerfile: Dockerfile
      args:
        DOMAIN_NAME: ${DOMAIN_NAME}
        ENVIRONMENT_TYPE: ${ENVIRONMENT_TYPE}
    container_name: nginx-proxy
    env_file:
      - .env
    ports:
      - "80:80"
      - "443:443"
    networks:
      - my_network
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/www/html:/var/www/html
    depends_on:
      - backend-development
    restart: always


networks:
  my_network:
    driver: bridge
