name: Development EC2 Instance Deployment
run-name: ${{ github.actor }} Changes Have Been Deployed!

on:
  push:
    branches:
      - ab-cicd-test-branch
    paths:
      - 'server_configs/docker-compose(staging).yml'  # Trigger if any file in the 'backend' directory changes

concurrency:
  group: "my-unique-group-name"
  cancel-in-progress: true

jobs:
  Deploy-To-EC2:
    runs-on: ubuntu-latest
    steps:
    - name: Creating PEM Key And Adding Host To Known Host
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_KEY" > ~/.ssh/bizznest.pem
        chmod 600 ~/.ssh/bizznest.pem

        # Add the EC2 instance to known_hosts
        ssh-keyscan "$DEVELOPMENT_IP" >> ~/.ssh/known_hosts
        chmod 644 ~/.ssh/known_hosts        
      env:
        SSH_KEY: ${{ secrets.SERVER_PRIVATE_KEY }}
        DEVELOPMENT_IP: ${{ secrets.DEVELOPMENT_SERVER_ADDRESS }}

  
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Connecting to EC2 and executing build commands
      run: |
        echo "Attempting To Update Configs"
        scp -i -vvv ~/.ssh/bizznest.pem $GITHUB_WORKSPACE/server_configs/docker-compose(staging).yml ubuntu@$DEVELOPMENT_IP:/home/ubuntu/configs/docker-compose.yml
        EOF
      env:
        DEVELOPMENT_IP: ${{ secrets.DEVELOPMENT_SERVER_ADDRESS }}
        

    - name: Remove Secrets
      run: |
        echo "Removing Secrets"
        rm -f ~/.ssh/bizznest.pem
