name: Updating Development Configs 
run-name: ${{ github.actor }} Changes Have Been Deployed!

on:
  push:
    branches:
      - ab-cicd-test-branch
    paths:
      - 'server_configs/**'  # Trigger if any file in the 'backend' directory changes

concurrency:
  group: "my-unique-group-name"
  cancel-in-progress: true

jobs:
  Deploy-To-EC2:
    runs-on: ubuntu-latest
    steps:   
    - name: Connecting to EC2 and executing build commands
      run: |
        # -- This updates the Configs yml file used for the docker containers, leverages interpolation
        echo "Attempting To Update Configs Template"
        scp -i ~/.ssh/bizznest.pem template.txt ubuntu@$DEVELOPMENT_IP:/home/ubuntu/configs/.env
        EOF
      env:
        DEVELOPMENT_IP: ${{ secrets.DEVELOPMENT_SERVER_ADDRESS }}
        ENV_ALLOW_ALL_ORIGINS: true
        ENV_SCRAPE_SCHEDULE: "${{ secrets.SCRAPE_SCHEDULE }}"
        ENV_CORS_ORIGIN: ${{ secrets.CORS_ORIGIN }}
        ENV_MAILGUN_API_KEY: ${{ secrets.MAILGUN_API_KEY }}
        ENV_MAILGUN_DOMAIN: ${{ secrets.MAILGUN_DOMAIN }}
        ENV_FROM_EMAIL: ${{ secrets.FROM_EMAIL }}
        ENV_REPORT_EMAIL: ${{ secrets.REPORT_EMAIL }}
        ENV_ENVIRONMENT_TYPE: ${{ secrets.DEVELOPMENT_ENVIRONMENT_TYPE }}
        ENV_DOMAIN_NAME: ${{ secrets.DEVELOPMENT_DOMAIN_NAME }}
        
        

    - name: Remove Secrets
      run: |
        echo "Removing Secrets"
        rm -f ~/.ssh/bizznest.pem
